name: "Security Scan (gosec)"

on:
  pull_request:
    branches: [ master, beta, development, test ]
  push:
    branches: [ master, beta, development, test ]

permissions: read-all

jobs:
  testsLinux:
    name: Tests (runs on Linux)
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2.22.10
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-exclude=G104,G307 -no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
